// import 'package:inovola_task/Features/home/data/models/expense.dart';
// import 'package:inovola_task/Features/home/data/data_sources/home_local_data_source.dart';
// import 'package:inovola_task/core/helpers/enums.dart';
// import 'package:inovola_task/core/networking/currency_service.dart';

// class AddExpense {
//   final HomeLocalDataSource _localDataSource;
//   // final CurrencyService _currencyService;

//   AddExpense(this._localDataSource, this._currencyService);

//   Future<void> call({
//     required String type,
//     required CategoriesEnum category,
//     required double amount,
//     required String currency,
//     required DateTime date,
//   }) async {
//     // Convert currency to USD
//     final conversionResult = await _currencyService.convertToUSD(
//       amount: amount,
//       fromCurrency: currency,
//     );

//     // Create expense model with converted values
//     final expense = Expense(
//       id: 0, // Will be auto-generated by Isar
//       type: type,
//       category: category,
//       amount: conversionResult.originalAmount,
//       currency: conversionResult.originalCurrency,
//       amountInUSD: conversionResult.convertedAmount,
//       exchangeRate: conversionResult.exchangeRate,
//       date: date,
//     );

//     // Save to local storage
//     await _localDataSource.saveExpense(expense);
//   }
// }
